### ISSUE TITLE
error when loading on macOS

### ISSUE THREAD

**Issue by yunikuneko** [alejandroautalan/pygubu#126]
```
$ pygubu-designer
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pygubu-designer", line 11, in <module>
    load_entry_point('pygubu==0.9.8.1', 'gui_scripts', 'pygubu-designer')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygubudesigner/main.py", line 46, in <module>
    from .uitreeeditor import WidgetsTreeEditor
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygubudesigner/uitreeeditor.py", line 31, in <module>
    from .widgeteditor import WidgetEditor
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygubudesigner/widgeteditor.py", line 28, in <module>
    from pygubudesigner.propertieseditor import PropertiesEditor
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygubudesigner/propertieseditor.py", line 31, in <module>
    from pygubudesigner.i18n import translator as _
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygubudesigner/i18n.py", line 32, in <module>
    lc, encoding = locale.getdefaultlocale()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 562, in getdefaultlocale
    return _parse_localename(localename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

**Comment by yunikuneko** [comment]
This occurs when first trying to launch pygubu from iTerm on macOS Sierra running python v3.6.2, instantly crashes with this dumped into the terminal.

**Comment by alejandroautalan** [comment]
Hello Mio Akemi, thanks for trying pygubu.

I think that this is a python issue on macOS, see https://bugs.python.org/issue18378

Try adding these lines to your ~/.bash_profile:

    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8

Let me know if that works.

Regards
Alejandro A.

**Comment by yunikuneko** [comment]
just occurred something interesting in trying that... it can no longer find `pygubu-designer` >.>

**Comment by yunikuneko** [comment]
`$ pygubu-designer
-bash: pygubu-designer: command not found`

**Comment by yunikuneko** [comment]
It appears to definitely be installed 😕 
```bash
$ pip3.6 install pygubu
Requirement already satisfied: pygubu in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requirement already satisfied: appdirs>=1.3 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pygubu)
```

**Comment by yunikuneko** [comment]
Attempted to reinstall using `pip3.6 uninstall pygubu` then reinstalled with `pip3.6 install pygubu` and it's still struggling to find pygubu 😢 
```bash
$ pygubu-designer
-bash: pygubu-designer: command not found
```
Do you have any clue what could be causing this one @alejandroautalan?

**Comment by alejandroautalan** [comment]
Hi Mio.
I can not help you much since I do not have access to a mac.

Some tips.
* Did you created the .bash_profile?  It should not be empty, copy one from the system directory like /etc. Then add the lines I passed you at the end.
* If you created the file, try deleting it. Then add the lines to .profile (other file)
* Last try. Remove any changes you made to your files. Try to run pygubu with:
    LC_ALL=en_US.UTF-8; LANG=en_US.UTF-8; pygubu-designer

Hope this helps.
Regards
Alejandro A

**Comment by yunikuneko** [comment]
Fixed 🙌 
In terms of fixing the not found error, there's a script in `/Applications/Python 3.6/` called `Update Shell Profile.command` which fixed the not found error, and to fix the original issue, creating `.bash_profile` and adding:
```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
worked perfectly, pygubu now runs 👌
For some reason when I created the .bash_profile I think it somehow nuked my $PATH variables... which caused the not found >.< Thanks for the help @alejandroautalan! ^.^

**Comment by MrJDHog** [comment]
The above didn't work for me, any other ideas?

**Comment by alejandroautalan** [comment]
Hi JDHog, thanks for trying pygubu.

Note that if you use pip to instal pygubu it will install all dependencies required.
If you use setup.py to install, you nedd to install manually the appdirs package.

Do you see an error message?
Let me know.

Regards.
Alejandro A.

**Comment by MrJDHog** [comment]
Hi Alejandro
The application opens without a problem and it seems to run until I make a multi touch swipe action on the Mac tracker pad. If I use a single finger there isn’t a problem. But two fingers cause pygubu to crash
Any ideas
Jason

**Comment by alejandroautalan** [comment]
Maybe is a tk or tkinter problem on multitouch support.
Can you run pygubu from a console and paste the error when it crash? If there is any.

Thanks.
Alejandro A.

**Comment by MrJDHog** [comment]
Hi Alejandro,
The first error which don’t seem to cause a problem happens when i open a file.

The second, crashed the app

**Comment by RuBiCK** [comment]
I'm fancing the same issue. It crashes under some circumstances like use two fingers in the trackpad:

```
wade:~ rubick$ pygubu-designer
python version: 3.6.3 on darwin
pygubu version: 0.9.8.2
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pygubu-designer", line 11, in <module>
    load_entry_point('pygubu==0.9.8.2', 'gui_scripts', 'pygubu-designer')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygubudesigner/main.py", line 558, in start_pygubu
    app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygubu/__init__.py", line 44, in run
    self.toplevel.mainloop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1277, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
I have setup the locale as commented in other issues
```
wade:~ rubick$ env | grep -i utf
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
```
