### ISSUE TITLE
Scrolling inside window causes UnicodeDecodeError

### ISSUE THREAD

**Issue by danton721** [alejandroautalan/pygubu#134]
Scrolling mouse inside window causes a fatal error. Python 3.6 on OS X

`Traceback (most recent call last):
  File "/usr/local/bin/pygubu-designer", line 11, in <module>
    sys.exit(start_pygubu())
  File "/usr/local/lib/python3.6/site-packages/pygubudesigner/main.py", line 545, in start_pygubu
    app.run()
  File "/usr/local/lib/python3.6/site-packages/pygubu/__init__.py", line 44, in run
    self.toplevel.mainloop()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1277, in mainloop
    self.tk.mainloop(n)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
`

**Comment by alejandroautalan** [comment]
Hello danto721, thanks for trying pygubu and sorry for the late response.

It Seems that this is a Tk bug on osx, see these links.:
http://stackoverflow.com/questions/16995969/inertial-scrolling-in-mac-os-x-with-tkinter-and-python
http://bugs.python.org/issue10731
https://sourceforge.net/p/tktoolkit/bugs/2966/

I can not investigate further because I do not have access to a mac system.

Regards.
Alejandro A.

**Comment by BaldEagleX02** [comment]
I had the same issue. It was a Tk bug, but the new version has just fixed it.
