### ISSUE TITLE
not run into OpenBSD 6.2

### ISSUE THREAD

**Issue by hucste** [alejandroautalan/pygubu#139]
Hello. 
I'm working on OpenBSD 6.2 - actual stable. 
I installed python3.6 

No problem to install by pip3, or by 'python3 setup...'.
The problem appear when i attempt to execute 'pygubu-designer', as : 

```
$ pygubu-designer                                                                                
python version: 3.6.2 on openbsd6
pygubu version: 0.9.8.2
Traceback (most recent call last):
  File "/usr/local/bin/pygubu-designer", line 11, in <module>
    load_entry_point('pygubu==0.9.8.2', 'gui_scripts', 'pygubu-designer')()
  File "/usr/local/lib/python3.6/site-packages/pygubudesigner/main.py", line 551, in start_pygubu
    app = PygubuUI(root)
  File "/usr/local/lib/python3.6/site-packages/pygubu/__init__.py", line 27, in __init__
    self._create_ui()
  File "/usr/local/lib/python3.6/site-packages/pygubudesigner/main.py", line 158, in _create_ui
    self.builder.get_object('mainwindow', self.master)
  File "/usr/local/lib/python3.6/site-packages/pygubu/builder/__init__.py", line 323, in get_object
    bobject = self._realize(root, node)
  File "/usr/local/lib/python3.6/site-packages/pygubu/builder/__init__.py", line 369, in _realize
    child = self._realize(parent, child_xml)
  File "/usr/local/lib/python3.6/site-packages/pygubu/builder/__init__.py", line 369, in _realize
    child = self._realize(parent, child_xml)
  File "/usr/local/lib/python3.6/site-packages/pygubu/builder/__init__.py", line 369, in _realize
    child = self._realize(parent, child_xml)
  [Previous line repeated 1 more times]
  File "/usr/local/lib/python3.6/site-packages/pygubu/builder/__init__.py", line 372, in _realize
    parent.configure()
  File "/usr/local/lib/python3.6/site-packages/pygubu/builder/widgets/scrolledframe.py", line 22, in configure
    super(TTKScrolledFrameBO, self).configure(self.widget.innerframe)
  File "/usr/local/lib/python3.6/site-packages/pygubu/builder/builderobject.py", line 100, in configure
    self._set_property(target, pname, value)
  File "/usr/local/lib/python3.6/site-packages/pygubu/builder/widgets/scrolledframe.py", line 26, in _set_property
    super(TTKScrolledFrameBO, self)._set_property(self.widget, pname, value)
  File "/usr/local/lib/python3.6/site-packages/pygubu/builder/builderobject.py", line 122, in _set_property
    target_widget[pname] = propvalue
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 1486, in __setitem__
    self.configure({key: value})
  File "/usr/local/lib/python3.6/site-packages/pygubu/widgets/tkscrolledframe.py", line 259, in configure
    self._configure_mousewheel()
  File "/usr/local/lib/python3.6/site-packages/pygubu/widgets/tkscrolledframe.py", line 277, in _configure_mousewheel
    self.hsb.on_mousewheel = BindManager.make_onmousewheel_cb(self, 'x', 2)
  File "/usr/local/lib/python3.6/site-packages/pygubu/binding.py", line 101, in make_onmousewheel_cb
    return on_mousewheel
UnboundLocalError: local variable 'on_mousewheel' referenced before assignment

```

Any idea?

**Comment by alejandroautalan** [comment]
Hi hucste, thanks for trying pygubu, and sorry for the late response.

It's a bug on pygubu code.
The function 'on_mousewheel' does not get defined for your platform.

I wil try to fix the code as soon as posible, but you can try to modifiy the method **make_onmousewheel_cb** on file 'pygubu/binding.py' with the flollowing:

```python
    @staticmethod
    def make_onmousewheel_cb(widget, orient, factor = 1):
        """Create a callback to manage mousewheel events
        
        orient: string (posible values: ('x', 'y'))
        widget: widget that implement tk xview and yview methods
        """
        _os = platform.system()
        view_command = getattr(widget, orient+'view')
        if _os == 'Linux':
            def on_mousewheel(event):
                if event.num == 4:
                    view_command("scroll",(-1)*factor,"units")
                elif event.num == 5:
                    view_command("scroll",factor,"units") 
        
        elif _os == 'Windows':
            def on_mousewheel(event):        
                view_command("scroll",(-1)*int((event.delta/120)*factor),"units") 
        
        elif _os == 'Darwin':
            def on_mousewheel(event):        
                view_command("scroll",event.delta,"units")
        else:
            # asume that we are on a linux like platform
            def on_mousewheel(event):
                if event.num == 4:
                    view_command("scroll",(-1)*factor,"units")
                elif event.num == 5:
                    view_command("scroll",factor,"units") 
        
        return on_mousewheel
```

Let me know if this work in your platfom.
Regards.
Alejandro A.

**Comment by hucste** [comment]
Hi, Alejandro.

New error: 

```
$ pygubu-designer                                                                       
python version: 3.6.2 on openbsd6
pygubu version: 0.9.8.2
No protocol specified
No protocol specified
Traceback (most recent call last):
  File "/usr/local/bin/pygubu-designer", line 11, in <module>
    load_entry_point('pygubu==0.9.8.2', 'gui_scripts', 'pygubu-designer')()
  File "/usr/local/lib/python3.6/site-packages/pygubudesigner/main.py", line 549, in start_pygubu
    root = tk.Tk()
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0.0"

```

**Comment by alejandroautalan** [comment]
Hi

> Because your code into final else is same into "if os == Linux", 
> If i understand really your code, just transform the line 86 to adding `or _os == 'OpenBSD'`, as: 
> 
> `if _os == 'Linux' or _os == 'OpenBSD':`

That is ok.

>   File "/usr/local/lib/python3.6/tkinter/__init__.py", line 2017, in __init__
>    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
> _tkinter.TclError: couldn't connect to display ":0.0"

You need to have the xserver running.
Try running pygubu-designer from a xterminal.

I downloaded openbsd configured python3 pygubu and xserver and is working.
Now I'm working on the final patch.

Let me know.
Regards
Alejandro A.

**Comment by hucste** [comment]
> You need to have the xserver running.
> Try running pygubu-designer from a xterminal.

Hu, sorry... but i use OpenBSD with Xfce, and launch 'pygubu-designer' into xfce's terminal ! :(

Ok, i founded: it's a problem into this terminal. I kill, and test into another: its ok!

Ty...

**Comment by hucste** [comment]
Perhaps, change your line 86, as:

```
unixes = ( 'Linux', 'OpenBSD, 'FreeBSD', )
if _os in unixes:
```

**Comment by alejandroautalan** [comment]
Hello, I think that you need to manually remove the folders and files:

    /usr/local/lib/python3.6/sitepackages/pygubu
    /usr/local/bin/pygubu-designer

Then install using pip3.
