### ISSUE TITLE
Requires appdirs, but its already installed. I tried reinstalling it

### ISSUE THREAD

**Issue by ILYEEV** [alejandroautalan/pygubu#156]
MacBook-Air-la-2:~ com$ pygubu-designer
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/pygubu-designer", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'appdirs>=1.3' distribution was not found and is required by pygubu
MacBook-Air-la-2:~ com$ pip3.6 install appdirs
Requirement already satisfied: appdirs in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (1.4.3)
MacBook-Air-la-2:~ com$

**Comment by ILYEEV** [comment]
the fix was to install it from the folder
