### ISSUE TITLE
Issue with get_object showing "wrong # args"

### ISSUE THREAD

**Issue by Kyle-Falconer** [alejandroautalan/pygubu#69]
When I try running the following code, I get an error saying `wrong # args` for the `builder.get_object` function:
### code:

```
import sys
import os

try:
    import tkinter as tk
    from tkinter import messagebox
except:
    import Tkinter as tk
    import tkMessageBox as messagebox

#sys.path.append(os.path.join(os.path.dirname(__file__), '../'))
import pygubu

class Myapp:
    def __init__(self, master):
        self.builder = builder = pygubu.Builder()
        fpath = os.path.join(os.path.dirname(__file__),"uploader.ui")
        builder.add_from_file(fpath)
        mainwindow = builder.get_object('mainwindow', master)

if __name__ == '__main__':
    root = tk.Tk()
    app = Myapp(root)
    root.mainloop()
```
### error output:

```
Traceback (most recent call last):
  File "gui.py", line 47, in <module>
    app = Myapp(root)
  File "gui.py", line 29, in __init__
    mainwindow = builder.get_object('main_window', master)
  File "/usr/local/lib/python2.7/site-packages/pygubu/builder/__init__.py", line 323, in get_object
    bobject = self._realize(root, node)
  File "/usr/local/lib/python2.7/site-packages/pygubu/builder/__init__.py", line 369, in _realize
    child = self._realize(parent, child_xml)
  File "/usr/local/lib/python2.7/site-packages/pygubu/builder/__init__.py", line 372, in _realize
    parent.configure()
  File "/usr/local/lib/python2.7/site-packages/pygubu/builder/builderobject.py", line 100, in configure
    self._set_property(target, pname, value)
  File "/usr/local/lib/python2.7/site-packages/pygubu/builder/builderobject.py", line 237, in _set_property
    target_widget.insert('0', value)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 2517, in insert
    self.tk.call(self._w, 'insert', index, string)
_tkinter.TclError: wrong # args: should be ".4406291344.4406342144 insert index text"
```

I'm on Mac OS 10.11.5 (15F34) using Python 2.7.11

**Comment by alejandroautalan** [comment]
Hello Kyle, thanks for trying pygubu.

Can you pass me the uploader.ui file that you are using (or a simplified version where the error occurs)?
And the pygubu version number, so I can reproduce the error.

Regards.
Alejandro A.
