### ISSUE TITLE
Exception with not found bitmaps

### ISSUE THREAD

**Issue by nuno-andre** [alejandroautalan/pygubu#83]
I got an exception when trying to add some deafult bitmaps to a menu element.

    C:\Anaconda3\Scripts>c:\anaconda3\python.exe -m pygubudesigner
    python version: 3.5.1 on win32
    pygubu version: 0.9.7.9
    Exception in Tkinter callback
    Traceback (most recent call last):
    File "c:\anaconda3\lib\tkinter\__init__.py", line 1549, in __call__
        return self.func(*args)
    File "c:\anaconda3\lib\site-packages\pygubudesigner\propertieseditor.py", line 95, in on_change_cb
        self._on_property_changed(pname, editor)
    File "c:\anaconda3\lib\site-packages\pygubudesigner\propertieseditor.py", line 102, in _on_property_changed
        self._current.set_property(name, editor.value)
    File "c:\anaconda3\lib\site-packages\pygubudesigner\widgetdescr.py", line 52, in set_property
        self.notify('PROPERTY_CHANGED', self)
    File "c:\anaconda3\lib\site-packages\pygubudesigner\util\observable.py", line 39, in notify
        observer.update_event(hint, self)
    File "c:\anaconda3\lib\site-packages\pygubudesigner\uitreeeditor.py", line 603, in update_event
        self.draw_widget(item)
    File "c:\anaconda3\lib\site-packages\pygubudesigner\uitreeeditor.py", line 105, in draw_widget
        self.previewer.draw(item, widget_id, xmlnode, wclass)
    File "c:\anaconda3\lib\site-packages\pygubudesigner\previewer.py", line 534, in draw
        preview.update(widget_id, xmlnode)
    File "c:\anaconda3\lib\site-packages\pygubudesigner\previewer.py", line 170, in update
        self.create_preview_widget(canvas_window, widget_id, xmlnode)
    File "c:\anaconda3\lib\site-packages\pygubudesigner\previewer.py", line 215, in create_preview_widget
        widget = self.builder.get_object(widget_id, menubutton)
    File "c:\anaconda3\lib\site-packages\pygubu\builder\__init__.py", line 323, in get_object
        bobject = self._realize(root, node)
    File "c:\anaconda3\lib\site-packages\pygubu\builder\__init__.py", line 369, in _realize
        child = self._realize(parent, child_xml)
    File "c:\anaconda3\lib\site-packages\pygubu\builder\__init__.py", line 361, in _realize
        widget = parent.realize(master)
    File "c:\anaconda3\lib\site-packages\pygubu\builder\tkstdwidgets.py", line 530, in realize
        master.add(tk.CASCADE, **item_properties)
    File "c:\anaconda3\lib\tkinter\__init__.py", line 2723, in add
        self._options(cnf, kw))
    _tkinter.TclError: bitmap "document" not defined`

**Comment by alejandroautalan** [comment]
Hello nuno-andre, thanks for trying pygubu.

You found a bug, Great! The availability of bitmaps depends on the running platform.  In this case, the bitmap "document" it is only defined on Macintosh.

The combobox for selecting a bitmap should list only available bitmaps depending on the platform.
I will fixit as soon as posible.

Regards
Alejandro A.

**Comment by nuno-andre** [comment]
Great! I'm trying it to develop a GUI for an application and it's a great tool.

I'll get around to make some contributions when I have more time.

Regards!
